
package ventanas;

import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Dimension ;
import javax.swing.ImageIcon;
/**
 *
 * @author JUNIOR SILVA
 */
public class panelFondo extends JPanel {

    /**
     * Creates new form panelFondo
     */
    public panelFondo() {
        initComponents();
    }

    
    
    @Override
public void paint (Graphics g){
    
   Dimension dim = this.getSize();
    ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/fondo_mar.jpg")) ;
   g.drawImage(fondo.getImage(),0 , 0, dim.width, dim.height, null) ;
   this.setOpaque(false);
   super.paintChildren(g);
   
   
    
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
